# Generated by Django 4.1.3 on 2022-11-27 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("active", models.IntegerField(default=1)),
                ("logo", models.CharField(blank=True, max_length=250, null=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
            ],
            options={
                "db_table": "brand",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                ("logo", models.CharField(blank=True, max_length=250, null=True)),
                ("active", models.IntegerField(default=1)),
                (
                    "parent",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="ecommerce.category",
                    ),
                ),
            ],
            options={
                "db_table": "categories",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Products",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=2500, null=True),
                ),
                ("logo", models.CharField(blank=True, max_length=250, null=True)),
                ("active", models.IntegerField(default=1)),
                ("deleted", models.IntegerField(default=0)),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="product_brand_rel",
                        to="ecommerce.brand",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_category_rel",
                        to="ecommerce.category",
                    ),
                ),
            ],
            options={
                "db_table": "products",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="ProductReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("max", models.DecimalField(decimal_places=2, max_digits=8)),
                ("value", models.DecimalField(decimal_places=2, max_digits=8)),
                ("comment", models.CharField(blank=True, max_length=4000, null=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="product_review_product_id_rel",
                        to="ecommerce.products",
                    ),
                ),
            ],
            options={
                "db_table": "product_review",
                "managed": True,
            },
        ),
    ]
