# Generated by Django 4.1.3 on 2022-11-27 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="products",
            name="price",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="products",
            name="description",
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
